### ISSUE TITLE
3.16

### ISSUE THREAD

**Issue by Thijzer** [coderstephen/pushbullet-gnome#4]
Hi, I'm trying to get the extension to work on 3.16 but no luck so far (nothing changed after restart).
I simply changed the metadata.json added 3.16 .

Are there any docs relating to the changes from 3.14 -> 3.16 
so I can take a deeper look and maybe fix the problem.

PS: plugin never worked for me so it might be something else, I just assumed it is because of the version change.

**Comment by marmis85** [comment]
hello,
if you want to try things out I'm continuing development [in my fork in the websocket branch](https://github.com/marmis85/pushbullet-gnome/tree/websocket).
As of now it kinda works for receiving pushes, after install you have to set your API key in the extension preferences and restart the extension.
The extensions saves in gsettings the last time it contacted the pushbullet api servers in order to pass the modified_after parameter to the api calls, if you want to reset that you have to do it manually with dconf by setting last-checked to 0.
There is an outstanding issue that I'm aware of: if you get it working, after deleting the last notification, notifications will stop working and you have to restart the extension... I have a fix for that but I haven't pushed the latest commits yet.

**Comment by dinojr** [comment]
Hi marmis85. Is your forked supposed to be working in gnome 3.18? I justed bumped the version number in metada.json, put in a pushbullet API key, but no luck so far.

**Comment by marmis85** [comment]
@dinojr I haven't been using this anymore for a while, but in theory it should, and it's still working for me on 3.20 after updating metadata.json.
What branch have you checked out? You should checkout master as I merged the websocket branch and made a couple more commits at the time.

**Comment by dinojr** [comment]
marmis85 notifications@github.com writes:

> @dinojr I haven't been using this anymore for a while, but in theory it should, and it's still working for me on 3.20 after updating metadata.json.
> What branch have you checked out? You should checkout master as I
> merged the websocket branch and made a couple more commits at the
> time.

I'm on master. The extension is "on" according to
https://extensions.gnome.org/local/, I've filled in the API key from
pushbullet.

Does the extension have its own icon in the top bar or does it use the
notification frame from the calendar?

Where should I look for error messages ?

Regards,

Julien.

**Comment by marmis85** [comment]
@dinojr the extension was (and still is) in a very early stage.
There is no indicator on the top panel and it only lets you receive pushes (sent to any device) in the form of standard desktop notifications.

If there are any errors you should see them in Looking Glass (ALT+F2, type "lg" in the command box) or in systemd's journal (journalctl /usr/bin/gnome-shell -f -o cat)

**Comment by dinojr** [comment]
marmis85 notifications@github.com writes:

> @dinojr the extension was (and still is) in a very early stage.  There
> is no indicator on the top panel and it only lets you receive pushes
> (sent to any device) in the form of standard desktop notifications.

I should receive notifications when my phone receives a sms, like I do
with the chrome pushbullet extension, right ?

> If there are any errors you should see them in Looking Glass (ALT+F2,
> type "lg" in the command box) or in systemd's journal (journalctl
> /usr/bin/gnome-shell -f -o cat)

I don't have any error message in either.

I've checked my API key with:
curl --header 'Access-Token: <your_access_token_here>' https://api.pushbullet.com/v2/users/me.
and it's correct. Is there a curl command I could try to check where
it's failing ?

Regards,

Julien.

**Comment by marmis85** [comment]
> I should receive notifications when my phone receives a sms, like I do with the chrome pushbullet extension, right ?

Sadly no, the only feature that is implemented is the reception of "pushes" (text, links and files) which is what I needed at the time :cry: 

The feature you are looking for is the Mirrored Notifications, the "backbone" would actually be already there but I never implemented the handling of what in the pushbullet jargon is called [Ephemerals](https://docs.pushbullet.com/#ephemerals) that includes Mirrored Notifications

If your are mainly interested in Mirrored Notification, some time ago I read of [Nuntius](https://github.com/holylobster/nuntius-linux) and the companion [Android App](https://github.com/holylobster/nuntius-android) but I don't know the status of the project (hasn't been updated in a while) and I think that requires a bluetooth connection between PC and Phone

**Comment by dinojr** [comment]
marmis85 notifications@github.com writes:

> > I should receive notifications when my phone receives a sms, like I do with the chrome pushbullet extension, right ?
> 
> Sadly no, the only feature that is implemented is the reception of
> "pushes" (text, links and files) which is what I needed at the time
> :cry:

Sorry, I had missed that part. I just tested the pushes, it works
indeed.

> The feature you are looking for is the Mirrored Notifications, the
> "backbone" would actually be already there but I never implemented the
> handling of what in the pushbullet jargon is called
> [Ephemerals](https://docs.pushbullet.com/#ephemerals) that includes
> Mirrored Notifications
> 
> If your are mainly interested in Mirrored Notification, some time ago
> I read of [Nuntius](https://github.com/holylobster/nuntius-linux) and
> the companion [Android
> App](https://github.com/holylobster/nuntius-android) but I don't know
> the status of the project (hasn't been updated in a while) and I think
> that requires a bluetooth connection between PC and Phone

I can survive with the chrome extension for pushbullet.

Thanks for your help.

Julien.
